import { CommitteeHead } from "./committee-head";

export const COMMITTEEHEADS: CommitteeHead[] = [
  // { name: '',
  // committee: '',
  // image: '',
  // office: '',
  // meetingTime: '',
  // responsibilities: '' },
  // DIRECTOR
  { name: 'Lana Verschage (She/Her/Hers)',
  committee: 'Director of Women in Computing ',
  image: '../../../../../../assets/committeeHeads/LanaDirector.PNG',
  office: 'Office: GOL-2371',
  meetingTime: 'General Meetings: Wed • 6:30pm',
  responsibilities: 'Responsible for the development of all programs, events, presentations, communications and marketing associated with Women in Computing at RIT whose purpose is to motivate and inspire girls and young women to choose computing as a profession and to recruit and retain women students for the Golisano College of Computing at RIT.' },
  //STAFF SPECIALIST
  { name: 'TBD',
  committee: 'Sr. Staff Specialist of Women in Computing ',
  image: '../../../../../../assets/committeeHeads/committeeHeadPlaceholder.jpg',
  office: 'Office: GOL-2371',
  meetingTime: 'General Meetings: Wed • 6:30pm',
  responsibilities: 'Supports recruiting and retention efforts for women and ALANA students in GCCIS. Manages logistics and administrative activities for all programs, events, presentations, communications, and marketing initiatives. Some of these events include, our annual WiCHacks, Accepted Student Overnight Program, WiC After-Hours and K-12 outreach programs. Also manages day to day operations in the new WiC spaces (2372 & 2350).' },
  //LOGISTICS
  { name: 'Jaime Campanelli (She/Her/Hers)',
  committee: 'Logistics',
  image: '../../../../../../assets/committeeHeads/JaimeLogistics.JPG',
  office: '',
  meetingTime: '',
  responsibilities: 'The responsibilities of Logistics are to assist the Director, maintain WiC calendar, send updates regarding upcoming events, maintain membership information, and maintain historical information.' },
  //PUBLIC RELATIONS 1
  { name: 'Hanna Koh',
  committee: 'Public Relations',
  image: '../../../../../../assets/committeeHeads/committeeHeadPlaceholder.jpg',
  office: '',
  meetingTime: '',
  responsibilities: 'The responsibilities of Public Relations committee are to update and maintain Social Media, brochures and newsletters. They are also responsible for scheduling company tech talks, info sessions and cultivating relationships with university recruiters at the RIT career fair. This committee plans and executes WiConnects, a networking event for Golisano faculty, students and WiC Allies.' },
  //PUBLIC RELATIONS 2
  { name: 'Peyton Wagner',
  committee: 'Public Relations',
  image: '../../../../../../assets/committeeHeads/committeeHeadPlaceholder.jpg',
  office: '',
  meetingTime: '',
  responsibilities: 'The responsibilities of Public Relations committee are to update and maintain Social Media, brochures and newsletters. They are also responsible for scheduling company tech talks, info sessions and cultivating relationships with university recruiters at the RIT career fair. This committee plans and executes WiConnects, a networking event for Golisano faculty, students and WiC Allies.' },
  //OUTREACH 1
  { name: 'Caitlyn Cyrek',
  committee: 'Outreach',
  image: '../../../../../../assets/committeeHeads/committeeHeadPlaceholder.jpg',
  office: '',
  meetingTime: '',
  responsibilities: 'Responsibilities consist of planning and executing activities for the K-12 population such as After-Hours, the Accepted Student Overnight Program, secondary school visits to campus for tours and workshops, Orientation, College & Careers, Open Houses, Kids on Campus Summer Camp, and shadow visits from prospective students.' },
  //OUTREACH 2
  { name: 'Savannah Alfaro',
  committee: 'Outreach',
  image: '../../../../../../assets/committeeHeads/committeeHeadPlaceholder.jpg',
  office: '',
  meetingTime: '',
  responsibilities: 'Responsibilities consist of planning and executing activities for the K-12 population such as After-Hours, the Accepted Student Overnight Program, secondary school visits to campus for tours and workshops, Orientation, College & Careers, Open Houses, Kids on Campus Summer Camp, and shadow visits from prospective students.' },
  //EVENTS
  { name: 'Alex Jankowski',
  committee: 'Events',
  image: '../../../../../../assets/committeeHeads/committeeHeadPlaceholder.jpg',
  office: '',
  meetingTime: '',
  responsibilities: 'The responsibilities of the Events committee are to plan, advertise, and execute internal and external social events, student tech talks, outings, and combined events with other Golisano clubs. ' },
  //WICHACKS
  { name: 'TBD',
  committee: 'WiCHacks',
  image: '../../../../../../assets/committeeHeads/committeeHeadPlaceholder.jpg',
  office: '',
  meetingTime: '',
  responsibilities: 'The responsibilities of the WiCHacks committee are to plan and execute the annual WiC Hackathon, a women only hackathon. Planning includes obtaining company sponsors and mentors, scheduling API workshops and tech talks, and planning a Newbie Track for women who haven’t coded before.' },
  //PROJECTS
  { name: 'Alanna Luce',
  committee: 'Projects',
  image: '../../../../../../assets/committeeHeads/committeeHeadPlaceholder.jpg',
  office: '',
  meetingTime: '',
  responsibilities: 'The responsibilities of the Projects committee are to encourage students of all majors to come together and work on a project of interest that is fun and can grow students’ technical skills. The goal is to present the project at Imagine RIT.' },
  //WEBMASTER
  { name: 'Darlene Ardila',
  committee: 'Webmaster',
  image: '../../../../../../assets/committeeHeads/committeeHeadPlaceholder.jpg',
  office: '',
  meetingTime: '',
  responsibilities: 'The Webmaster is responsible for updating and maintaining the Women in Computing website and the WiCHacks website. The WiC website was revamped in 2019 by Lauren DiDonato and in 2021 by Amy Tan.' },
  //ALLIES
  { name: 'Mallory Bridge',
  committee: 'Allies',
  image: '../../../../../../assets/committeeHeads/MalAllies.jpg',
  office: '',
  meetingTime: '',
  responsibilities: 'WiC Allies is a group of RIT and GCCIS community members committed to furthering the mission and goals of Women in Computing, for the purpose of affecting positive change and fostering a more inclusive GCCIS culture.' },
]
